import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "@/components/icons";
import { ctfRecords, featuredCtf } from "@/content/ctfs";
import { credentials, profile, skillGroups, socialLinks } from "@/content/profile";
import { researchRecords } from "@/content/research";

export const metadata: Metadata = { title: "Resume", description: "Public professional resume for Vansh Marwaha, independent security researcher." };

export default function ResumePage() {
  return <main className="resume-page"><header><Link href="/">VM / Researcher</Link><span className="print-label">Public resume</span></header><section className="resume-hero"><p>Independent security researcher</p><h1>Vansh Marwaha</h1><div><span>Offensive security</span><span>Vulnerability research</span><span>CTFs</span></div></section><section className="resume-summary"><h2>Profile</h2><p>{profile.about}</p><div>{credentials.map((item) => <article key={item.label}><span>{item.label}</span><strong>{item.value}</strong><p>{item.detail}</p></article>)}</div></section><section><h2>Selected security research</h2><div className="resume-records">{researchRecords.map((record) => <article key={record.target}><div><h3>{record.target}</h3><span>{record.category}</span></div><p>{record.summary}</p></article>)}</div></section><section><h2>CTF & practical security</h2><div className="resume-records"><article><div><h3>{featuredCtf.event}</h3><span>{featuredCtf.meta}</span></div><p><strong>{featuredCtf.placement} {featuredCtf.caption}</strong> — {featuredCtf.badge}. {featuredCtf.note}</p></article>{ctfRecords.map((record) => <article key={record.event}><div><h3>{record.event}</h3><span>{record.kind}</span></div><p><strong>{record.result}</strong> — {record.detail}</p></article>)}</div></section><section className="resume-columns"><div><h2>Security practice</h2>{skillGroups.map((group) => <article key={group.title}><h3>{group.title}</h3><p>{group.skills.join(" · ")}</p></article>)}</div><div><h2>Certification</h2><article><h3>eJPT v2</h3><p>eLearnSecurity Junior Penetration Tester</p><a href={profile.certificationUrl} target="_blank" rel="noreferrer">Verify certificate <ArrowUpRight /></a></article></div></section><section><h2>Responsible disclosure</h2><ul className="resume-points">{profile.disclosurePoints.map((point) => <li key={point}>{point}</li>)}</ul><p className="resume-note">I conducted the research described above for responsible disclosure and/or authorized security testing. Sensitive secrets, personal data, and operational exploit details are intentionally omitted.</p></section><footer><a href={`mailto:${profile.email}`}>{profile.email}</a>{socialLinks.map((link) => <a key={link.label} href={link.href} target="_blank" rel="noreferrer">{link.label}</a>)}<Link href="/">Portfolio <ArrowRight /></Link></footer></main>;
}
